### ISSUE TITLE
Platform model

### ISSUE THREAD

**Issue by jaakop** [SprintWeekGRoup1/SprintWeekProject#21]

**Comment by Emiliontti** [comment]
Give PNG's for each separate platform model plx.

**Comment by Emiliontti** [comment]
.ai file already in the main project.

**Comment by Laffey-chan** [comment]
Some how when I export the png from the ai project the image sizes / platform's will be small

**Comment by Laffey-chan** [comment]
> Some how when I export the png from the ai project the image sizes / platform's will be small

So i need to find a way were the platforms will not be small

**Comment by Emiliontti** [comment]
The issues content was not functional when hitting the deadline. Closed without implementing.
