### ISSUE TITLE
Finish

### ISSUE THREAD

**Issue by jaakop** [SprintWeekGRoup1/SprintWeekProject#25]
The fruit basket should detect when the player reaches it. Once there it should trigger some winnig screen

**Comment by Laffey-chan** [comment]
This is now done with collider 2d that has added to the basket, show we can check if the player collides with the basket

**Comment by Laffey-chan** [comment]
The check is done in the player controller if the collides with the basket

**Comment by Emiliontti** [comment]
The branch that had these changes was not pushed to the remote before deadline. Assignee was changed, and needed to be redone.
