### ISSUE TITLE
Winning screen

### ISSUE THREAD

**Issue by jaakop** [SprintWeekGRoup1/SprintWeekProject#26]
Shown to the player when they win

**Comment by Laffey-chan** [comment]
Gonna reuse the Pause Menu for win menu just slite changes

**Comment by Laffey-chan** [comment]
This is done copied the pause menu and changed that the is next level button and text that says you win

**Comment by Emiliontti** [comment]
The branch that had these changes was not pushed to the remote before deadline. Assignee was changed, and needed to be redone.
