### ISSUE TITLE
GameManager (Win/Loose etc.)

### ISSUE THREAD

**Issue by jaakop** [SprintWeekGRoup1/SprintWeekProject#28]

**Comment by Laffey-chan** [comment]
The Lose is already with dead of the character, but there mauby should be added lose screen when player dies

**Comment by Laffey-chan** [comment]
Winning is just when the player collides with the basket and then the winning screen should pop up

**Comment by Laffey-chan** [comment]
> Winning is just when the player collides with the basket and then the winning screen should pop up

This is done

**Comment by Laffey-chan** [comment]
I might reuse the winnin screen and just change the text and button stuff to level failed and restart the game

**Comment by Emiliontti** [comment]
The content of this issue was implemented, but the assignee changed because the branch that had the changes wasn't pushed to the remote.
